export const NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY =
    process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY!;
export const CLERK_SECRET_KEY = process.env.CLERK_SECRET_KEY!;

export const NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL =
    process.env.NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL!;
export const NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL =
    process.env.NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL!;

export const NEXT_PUBLIC_CHAIN_NAME = process.env.NEXT_PUBLIC_CHAIN_NAME!;
export const NEXT_PUBLIC_API_URL = process.env.NEXT_PUBLIC_API_URL!;